name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false
      - name: Build with Gradle
        run: ./gradlew build
      - name: Get Version
        run: echo "MOD_VERSION=$(${{github.workspace}}/gradlew -q printVersion)" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
         name: ${{ github.event.repository.name }}-NeoForge
         path: ./NeoForge/build/libs/GatheringChunks-neoforge-${{MOD_VERSION}}.jar
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
         name: ${{ github.event.repository.name }}-Fabric
         path: ./Fabric/build/libs/GatheringChunks-fabric-${{MOD_VERSION}}.jar